version: '3'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - '/Users/jimmycui/proj/prometheus/elasticache/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - redis_exporter1
    #- redis_exporter2

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    ports:
      - '3000:3000'

  redis_exporter1:
    image: bitnami/redis-exporter:latest
    container_name: redis_exporter1
    ports:
    - 19121:9121
    command:
    - --redis.addr=
    depends_on:
    - redis1
    - redis2

  redis1:
    image: redis:latest
    container_name: redis1
    ports:
    - 16379:6379

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
    - 26379:6379
